### ISSUE TITLE
Usage guide? Push image to registry?

### ISSUE THREAD

**Issue by dumbasPL** [voruti/ShlinkDiscordBot#23]
It would be nice if there was a bit more information in the readme. From looking at the files I managed to figure out what is what but It would be nice if there was a simple quick start guide in the readme. Like describing how to build, configure, run, etc...

Also, I've noticed that the provided `docker-compose.yml` only has `build .` and doesn't have an image defined. Have you considered building and pushing the image to docker hub or ghcr.io (Github container registry)? This way people could use it without having to build it themselves.

**Comment by voruti** [comment]
I added *some* information about the installation.

I don't think publishing an image is necessary, because it's a rather small project and also building works on the fly and doesn't take long.

**Comment by dumbasPL** [comment]
> I don't think publishing an image is necessary, because it's a rather small project and also building works on the fly and doesn't take long.

Well, that's not true for all setups. If you're using just plain docker then yes, but in more advanced setups building on the fly can be problematic. I just wanted to have an official image available, but if not then I guess I'll have to maintain my own ¯\\\_(ツ)_/¯

**Comment by voruti** [comment]
Okay, then do it like this.
